name: Testing Kubectl

on: push
jobs:
  break:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version
      - name: Setup Kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          kubectl version --short --client