name: Getting Started Github Actions

on: push
env:
  IMAGE_NAME: hello
  REGISTRY_HOSTNAME: docker.pkg.github.com
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REPOSITORY: ${{ github.repository }}
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get service from ref
        run: |
          echo "왜 안나오지"
          echo "${{ github.ref }}"
          MODULE=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $MODULE

      - name: Build image
        run: docker build . -f Dockerfile --tag ${IMAGE_NAME}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${REGISTRY_HOSTNAME} -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ${IMAGE_NAME} ${REGISTRY_HOSTNAME}/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}
          docker push ${REGISTRY_HOSTNAME}/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}

  dump:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
